# permissions for end users to edit canaryrequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: canaryrequest-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: canary
    app.kubernetes.io/part-of: canary
    app.kubernetes.io/managed-by: kustomize
  name: canaryrequest-editor-role
rules:
- apiGroups:
  - canary.maborosii.com
  resources:
  - canaryrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - canary.maborosii.com
  resources:
  - canaryrequests/status
  verbs:
  - get
